### ISSUE TITLE
我应该将mirai-core放在哪里?

### ISSUE THREAD

**Issue by ghost** [Isla4ever/NukkitQQSync#1]

**Comment by 4o3F** [comment]
插件已经内置mirai，直接使用即可

**Comment by 4o3F** [comment]
@SeaIce233 (你没感觉插件大的很么😂)
没有其他问题的话，请close issue

**Comment by ghost** [comment]
[INFO ] 开启 NukkitQQ v0.1 中
[ERROR] Throwing
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:468) [powernukkit-1.3.1.5-PN-shaded.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:876) [powernukkit-1.3.1.5-PN-shaded.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:865) [powernukkit-1.3.1.5-PN-shaded.jar:?]
        at cn.nukkit.Server.<init>(Server.java:688) [powernukkit-1.3.1.5-PN-shaded.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit-1.3.1.5-PN-shaded.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at app.Isla4ever.NukkitQQ.onEnable(NukkitQQ.java:217) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:94) ~[powernukkit-1.3.1.5-PN-shaded.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:118) ~[powernukkit-1.3.1.5-PN-shaded.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:464) ~[powernukkit-1.3.1.5-PN-shaded.jar:?]
        ... 4 more
Caused by: java.lang.IllegalStateException: No BotFactory found. Please ensure that you've added dependency of protocol modules.
Available modules:
- net.mamoe:mirai-core-timpc (stays at 0.12.0)
- net.mamoe:mirai-core-qqandroid (recommended)
You should have at lease one protocol module installed.
-------------------------------------------------------
找不到 BotFactory. 请确保你依赖了至少一个协议模块.
可用的协议模块:
- net.mamoe:mirai-core-timpc (0.12.0 后停止更新)
- net.mamoe:mirai-core-qqandroid (推荐)
请添加上述任一模块的依赖(与 mirai-core 版本相同)
        at net.mamoe.mirai.BotFactoryJvm.<clinit>(BotFactory.kt:144) ~[?:?]
        at app.Isla4ever.NukkitQQ.onEnable(NukkitQQ.java:217) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:94) ~[powernukkit-1.3.1.5-PN-shaded.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:118) ~[powernukkit-1.3.1.5-PN-shaded.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:464) ~[powernukkit-1.3.1.5-PN-shaded.jar:?]
        ... 4 more
[INFO ] 关闭 NukkitQQ v0.1 中
[INFO ] [NukkitQQ] NukkitQQ disabled

**Comment by ghost** [comment]
> @SeaIce233 (你没感觉插件大的很么😂)
> 没有其他问题的话，请close issue

看一下😂

**Comment by 4o3F** [comment]
用最新的0.3版本试试看，powernukkit我没有测试过，试试原版的nukkit
@SeaIce233

**Comment by ghost** [comment]
> 用最新的0.3版本试试看，powernukkit我没有测试过，试试原版的nukkit
> @SeaIce233

用的就是0.3😂
换了nk也是一样

**Comment by ghost** [comment]
感觉是与某个插件冲突了

**Comment by 4o3F** [comment]
> 感觉是与某个插件冲突了

hmmmmm你尝试了把其他插件删掉了么？按理说应该不会冲突啊，我也很菜，所以拜托帮忙测试一下

**Comment by 4o3F** [comment]
确认是插件冲突问题，排查出来后会尽快修复
