### ISSUE TITLE
powernukkit报错

### ISSUE THREAD

**Issue by TheZhuDaXian** [Isla4ever/NukkitQQSync#3]
[34mINFO [m] 开启 NukkitQQ v0.6 中
[92m2021-06-23 17:58:45 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.[0m
[92m2021-06-23 17:58:45 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.[0m
java.lang.NullPointerException
at xiaokai.bemilk.ShopCommand.reload(ShopCommand.java:51)
at xiaokai.bemilk.mtp.startThread.run(startThread.java:79)
[36m17:58:46[m [[34mINFO [m] [BugReport] 侦测到一个错误，正在生成错误报告。
[36m17:58:46[m [[34mINFO [m] [BugReport] 创建错误报告：C:\Users\molu\Desktop\MCSManager_8.6.18_Win64\MCSManager_8.6.18_Win64\server\server_core\RC空岛\logs\bug_reports\20210623175846_NullPointerException.md
>java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
at javax.crypto.JceSecurity.getInstance(JceSecurity.java:105)
at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:230)
at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.
net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:56)
at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116)
at dev.cardinaldevlab.NukkitQQ.onEnable(NukkitQQ.java:210)
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:101)
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:459)
at cn.nukkit.Server.enablePlugin(Server.java:938)
at cn.nukkit.Server.enablePlugins(Server.java:927)
at cn.nukkit.Server.<init>(Server.java:765)
at cn.nukkit.Nukkit.main(Nukkit.java:199)
>Caused by: java.util.jar.JarException: file:/C:/Users/molu/Desktop/MCSManager_8.6.18_Win64/MCSManager_8.6.18_Win64/server/server_core/RC空岛/plugins/NukkitQQSync.jar has unsigned entries - config.yml
at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:502)
at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:363)
at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
... 17 more

**Comment by 4o3F** [comment]
@DYD520 hmmmmmmmm这我都不准备更新了，听我个建议的话，转去用Geyser吧
